# Generated by Django 4.2.6 on 2023-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
